Add key generation procedures
openpgp-pqc/draft-openpgp-pqc pull request #19
Opened 2023-01-25 23:24 UTC by wussler

This PR addresses #3

2023-01-30 12:12 UTC, falko-strenzke approved these changes

2023-01-31 04:52 UTC, fluppe2 commented on draft-wussler-openpgp-pqc.md
> +component keys. The dilithium component is generated as specified in
```suggestion
component keys. The Dilithium component is generated as specified in
```

2023-01-31 04:52 UTC, fluppe2 commented on draft-wussler-openpgp-pqc.md
> +component keys. The dilithium component is generated as specified in
Typo

2023-01-31 04:56 UTC, fluppe2 commented on draft-wussler-openpgp-pqc.md
> +To generate a SPHINCS+ key the function `spx_keygen()` specified in
```suggestion
The SPHINCS+ key generation is performed according to the function `spx_keygen()` specified in
```

2023-01-31 04:57 UTC, fluppe2 commented on draft-wussler-openpgp-pqc.md
> +To generate a SPHINCS+ key the function `spx_keygen()` specified in
There was something missing like "the function is used" in the previous sentence.

2023-01-31 05:00 UTC, fluppe2 commented on draft-wussler-openpgp-pqc.md
> +component keys. The dilithium component is generated as specified in
```suggestion
component keys. Dilithium key generation follows the specification in
```

2023-01-31 05:01 UTC, fluppe2 commented on draft-wussler-openpgp-pqc.md
> +component keys. The dilithium component is generated as specified in
Aligned to the text for Kyber, fixed typo.

2023-01-31 05:01 UTC, fluppe2 requested changes
Apart from the suggestions great for me.

2023-02-24 06:41 UTC, merged